use_frameworks!

platform :ios, '11.0'

target 'OCCustomComponent_Example' do
  pod 'OCCustomComponent', :path => '../'

  target 'OCCustomComponent_Tests' do
    inherit! :search_paths

    
  end
end
